### ISSUE TITLE
Richer set of examples

### ISSUE THREAD

**Issue by avi-stripe** [stripe/rainier#102]
It would be wonderful to have some more sophisticated models as examples than the toy ones that are currently there. @darrenjw, I believe you have some - would it make sense to contribute them to the repo?

**Comment by darrenjw** [comment]
Yes - I was thinking the same. I'll add a few ASAP.

**Comment by darrenjw** [comment]
I'm tidying up a few examples to contribute, but I've been using EvilPlot to visualise the output (high-res trace plots are still the best MCMC convergence diagnostic I know of...), which will presumably break travis. To do this I have developed some code for EvilPlot integration (addressing #50), which is a bit more sophisticated than the simple contour plot in the outstanding pull request.

Would you like me to contribute the examples with the EvilPlot code commented out, with a view to commenting back in when travis is happy with the added dependency, or would you prefer me to remove all traces of the EvilPlot code for now? Or just wait until the EvilPlot dependency is sorted before adding the examples?

**Comment by avi-stripe** [comment]
I think the best approach would be:

* put your `EvilPlot` code in a separate `rainier-plot` module which only builds under scala 2.12
* have `rainier-example` depend on `rainier-plot` so that you can use EvilPlot from there without commenting anything out

I don't think it's a problem for the examples to require 2.12 because nobody will need to include the example module as an artifact in their own projects.

**Comment by avi-stripe** [comment]
(If you need help with the separate modules and restricting the build to 2.12 I'm sure we can do that part)

**Comment by darrenjw** [comment]
We should perhaps leave this open for now. It would be good to have a bunch more examples. I've got a couple in the works, but still having some issues with sampling.
