### ISSUE TITLE
Tests for non-determinism

### ISSUE THREAD

**Issue by avi-stripe** [stripe/rainier#118]
I'm currently tracking down a problem where `.gradient` is non-deterministic (will sometimes return meaningfully different functions if you call it multiple times in the same process on the same target). Less dangerously, previously the ordering of `variables` could vary between runs which made debugging harder. We should have tests that ensure that these things are totally deterministic given the same RNG seed.

**Comment by avi-stripe** [comment]
The problem I was seeing was, I think, a numerical instability that was sensitive to the particular order in which terms of a sum or product were compiled to bytecode. See https://github.com/stripe/rainier/pull/119 for the model-specific fix that helped. As part of this issue (or a new one) we should provide automatic diagnostics for this kind of non-deterministic instability in user models.

**Comment by andyscott** [comment]
The arbitrary instances in #132 might help with testing for nondeterministic behavior.
