### ISSUE TITLE
Track bounds on Real

### ISSUE THREAD

**Issue by avi-stripe** [stripe/rainier#153]
It's extremely common for the support or parameterization of distributions to only be defined for R>0, R>=0, or 0<=R<=1. It's not feasible to fully type check this, but we might benefit from some simple wrappers around `Real` that force you to be a little more deliberate/explicit about such things, and possibly lead to more informative runtime errors when you get it wrong.

**Comment by avibryant** [comment]
Partially addressed by https://github.com/stripe/rainier/pull/420

**Comment by avibryant** [comment]
finished in https://github.com/stripe/rainier/pull/449
