### ISSUE TITLE
Now it has a Cats module...

### ISSUE THREAD

**Issue by kailuowang** [stripe/rainier#167]
Thank you guys so much for developing this awesome library. I haven't officially started using it in my projects yet, but I can see it being my best friend for the next couple of years. This kind of Pure Functional and high-performance ML libraries will be critical for the future success of Scala as a technology.
May I propose adding it to Cats' homepage as one of the projects that support Cats?

**Comment by andyscott** [comment]
Sure thing!

**Comment by kailuowang** [comment]
Thanks!
