### ISSUE TITLE
HMC Sampler hanging in some cases

### ISSUE THREAD

**Issue by mikeheaton-stripe** [stripe/rainier#174]
I've found two cases where the `HMC` sampler hangs but `Walkers` does not.

First, `Uniform(a,b).param.sample(HMC(5))` hangs when `a<0`;  `Uniform(a,b).param.sample(Walkers(100))` is fine.

Second, `Mixture(Map(Exponential(lambda) -> 0.5, Beta(0.1, 100) -> 0.5)).param.sample(HMC(5), 2000, 2000)` hangs when `lambda` is large (1e2 is ok but 1e3 fails).
`Mixture(Map(Exponential(lambda) -> 0.5, Uniform(0,1) -> 0.5)).param.sample(HMC(5), 2000, 2000)` is fine, as is `Mixture(Map(Exponential(lambda) -> 0.5, Beta(0.1, 100) -> 0.5)).param.sample(Walkers(100), 2000, 2000)`, and `Exponential(1e9).param.sample(HMC(5), 2000, 2000)`.

**Comment by avi-stripe** [comment]
Update: this is because underflow during log-sum-exp. Fixing this requires a working max() op, so this depends on adding that.
