### ISSUE TITLE
Docs say to use `Compiler.default` which no longer appears to exist.

### ISSUE THREAD

**Issue by espears4sq** [stripe/rainier#180]
In [the docs on Evaluator and Compiler](https://github.com/stripe/rainier/blob/master/docs/real.md#evaluator-and-compiler), there appears to be a bug with the example usage of `Compiler`. The code suggests to do this:

```
scala> val xyFn = Compiler.default.compile(List(x,y), xy)
xyFn: Array[Double] => Double = scala.Function1$$Lambda$22782/1507142391@2c8a37ce
```

However, when I build the project from master locally with sbt and enter `sbt "project rainierCore" console`, then use `import com.stripe.rainier.compute.{Evaluator, Compiler}`, I find that there is no `Compiler.default` and so the tutorial code cannot be executed.

I also noticed another comment at the very bottom about "compileGradient" which also does not seem to exist in the imported `Compile`.

Maybe I am missing something silly, let me know if there is a quick fix, or if the API of `Compiler` has just changed and is out of sync with the docs.

Thanks!

**Comment by avibryant** [comment]
`Compiler.default` is back now in the develop branch.
