### ISSUE TITLE
Can Rainier support vector-valued random variables?

### ISSUE THREAD

**Issue by espears4sq** [stripe/rainier#191]
In e.g. pymc I might write

```
import pymc as pm
beta = pm.Normal('beta', 0, 1, shape=100)
```

in a case when my observations have 100 feature components. Then when I later sample the model, each sampled value of beta will be a length-100 array of the individual component-wise samples.

How can I achieve the same thing in Rainier? In particular, for a model with a vector-valued parameter (say a large regression model), the user would not want to manually type out hundreds of different individual random variables in the format like

```
val model = for {
    beta0 <- Normal(0, 1).param 
    beta1 <- Normal(0, 1).param
    ...
    beta99 <- Normal(0, 1).param
    // rest of model likelihood here
} yield List(beta0, beta1, ..., beta99)
```

Is there a way to provide a shape parameter to make it vector / array / list valued?

**Comment by espears4sq** [comment]
Thanks again for so much help.

One limitation I am noticing is that this isn't directly compatible with the training data starting out in breeze.DenseMatrix or breeze.DenseVector formats (for example, breeze seems not to have a concept of zipping matrices with vectors at all). It results in making copies of the data with verbose conversions to List type, like

```
val rainierTrainingData = (for (r <- x(breeze.linalg.*, ::)) yield {
    r.toArray.toList).toArray.toList
  } zip y.toArray.toList
```

(I'm also noticing a lot of implicits errors with breeze mixed with rainier that I don't understand yet.)

Maybe I am missing something simple that would solve this? As the size of the feature set grows, there would become greater needs to keep it in a DenseMatrix format for preprocessing, etc. And ideally you'd like to be able to refer directly to breeze data structures inside the monadic model construction syntax.

**Comment by avi-stripe** [comment]
Interesting, I haven't looked closely at breeze, but I just created an issue to improve that integration. Thanks very much for the feedback.
