### ISSUE TITLE
Add `com.stripe.sampler.DensityFunction` trait

### ISSUE THREAD

**Issue by avibryant** [stripe/rainier#206]
As we invest in more complicated compiled representations of the density (allowing batch evaluation etc), it feels more like a leaky abstraction to have the `sampler` package directly interact with the compiler. I propose that we make `sampler` completely dependency-free, and expose a trait like the following, which clients (ie, `core`, making use of `compute`) can supply implementations of:

```scala
trait DensityFunction {
   def arity: Int
   def compute(params: Array[Double]): Double
   def computeGradient(params: Array[Double], gradient: Array[Double]): Double
}
```

All of the `sampler` implementations would be expressed in terms of this, taking it in place of the current `Context` object.

**Comment by mio-stripe** [comment]
Great, I'll start on this.
