### ISSUE TITLE
learn the mass matrix

### ISSUE THREAD

**Issue by avibryant** [stripe/rainier#220]
eg https://dfm.io/posts/pymc3-mass-matrix/

**Comment by springcoil** [comment]
This would be super cool. I've thought about sticking it in PyMC3 proper.

**Comment by avibryant** [comment]
See also https://github.com/eigenfoo/littlemcmc/blob/c3923508cccdb8e39859129c66cb1936d4a16f54/littlemcmc/quadpotential.py
