### ISSUE TITLE
batched support for hierarchical models

### ISSUE THREAD

**Issue by avibryant** [stripe/rainier#236]
Some kind of semantics that allow you to group observations  into sub-populations, each of which have their own copy of a parameter or parameters.

I have this somewhat cryptic note lying around in my editor on this subject that I leave here for posterity.

```scala
object RandomVariable {
  def group(seq: Seq[K])(fn: Tag => V): RandomVariable[Tag => V] 
  //or:
  def group(fn: Tag => V): RandomVariable[Tag => V] ?
}
```

**Comment by avibryant** [comment]
A very general approach that might work well is to have a `LookupReal(index: Real, table: Seq[Real])` whose semantics are that it evaluates to `num.toDouble(table(num.toInt(index)))`.
I'm confident we can generate efficient code for this in forwards mode, but not sure if we can also generate an efficient gradient for it.

**Comment by avibryant** [comment]
Actually I think it's fine for gradients too. A LookupReal with k values in `table` just becomes k `If` statements with a constant on one branch and where they all share the same other branch.

**Comment by roban-stripe** [comment]
Does "their own copy of a parameter or parameters" mean they are separate random variables, but you have an easy syntax for specifying that each of the groups need to have it's own set of these types of variables?

**Comment by avibryant** [comment]
@roban-stripe yeah, exactly. Here's some sample code that illustrates the kind of thing I'm thinking about:

```scala
//try to fit k different correlated normal distributions which have the same variance but different means
//and whose means are themselves distributed normally around some central mean
//the Int field of each data point indicates which normal it comes from
def model(data: Seq[(Int,Double), k: Int]) = 
   for {
      globalMean <- Normal(0,1).param
      stddev <- Exponential(1).param
      localMeans <- RandomVariable.fill(k)(Normal(globalMean, 1).param).map(Lookup(_))
      _ <- Predictor.fromInt{i => Normal(localMeans(i), stddev)}.fit(data)
   } yield (stddev, localMeans)
```

So, in this case, the code for the likelihood function defined in the `Predictor` line is only generated once, and each data point can be run through it, even though they are each only using/affecting a single one of the `localMeans` parameters.
