### ISSUE TITLE
0.2.0 M1 release? 

### ISSUE THREAD

**Issue by kailuowang** [stripe/rainier#278]
Is there any chance a 0.2.0-M1 can be released?  rainier-plot will be available on Scala 2.11 with this release.

**Comment by avibryant** [comment]
Oh, sorry - I did a hurried release of 0.2.0 on the day of my Scale by the Bay talk and forgot to tag it. But you're right that rainier-plot 2.11 is available: https://search.maven.org/search?q=a:rainier-plot_2.11
