### ISSUE TITLE
Any equivalent api of pm.math.switch ?

### ISSUE THREAD

**Issue by weiczhu** [stripe/rainier#406]
Hi Team,
I'm reading the suggested resources and found in their last example they use the 
"pm.math.switch"
as a condition operation.
https://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC3.ipynb

I recall that rainer only support pow,log and four basic arithmatic operations.
just wondering if any way to achieve the same purpose as the "pm.math.switch" ?
Thanks

**Comment by avibryant** [comment]
In a limited way, yes. What you want are these methods on the `Real` object, which combine a switch-equivalent with numeric comparison operators:
https://github.com/stripe/rainier/blob/develop/rainier-core/src/main/scala/com/stripe/rainier/compute/Real.scala#L90
