### ISSUE TITLE
Add integration with EvilPlot

### ISSUE THREAD

**Issue by avi-stripe** [stripe/rainier#50]
https://github.com/cibotech/evilplot

Just in case someone isn't hipster enough to appreciate my ASCII plots.

**Comment by hibikir** [comment]
How good do you want the integration to be? If all you want is to be able to generate some contours, I have a 5 line implementation in my fork that I'll be happy to contribute. This is the bonus file output of one of the examples.
![plot](https://user-images.githubusercontent.com/7410363/40594114-ae233024-61f2-11e8-9990-62e41dd5bf76.png)

**Comment by avi-stripe** [comment]
By all means, love to have the contribution.

**Comment by darrenjw** [comment]
I think we can probably close this one.
