### ISSUE TITLE
L-BFGS optimizer

### ISSUE THREAD

**Issue by avi-stripe** [stripe/rainier#87]
https://en.wikipedia.org/wiki/Limited-memory_BFGS

**Comment by roban-stripe** [comment]
Is this for implementing MAP or are there other things we'd want to optimize?

**Comment by avi-stripe** [comment]
`MAP` is what I'm thinking of, but it's also possible that there would be uses of the compute layer other than bayesian inference for which optimization would be valuable.

**Comment by fommil** [comment]
I know you're proud of the no-JNI, but your gradient calculations are big enoughyou could always use https://github.com/fommil/netlib-java and only depend on the JVM implementation. It would be a suitable abstraction for an optimised BFGS impl and end users could swap out for an MKL native at runtime, if they want.

**Comment by avibryant** [comment]
Worth checking out https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/optimize/LBFGS.scala
