### ISSUE TITLE
Snapshot releases

### ISSUE THREAD

**Issue by darrenjw** [stripe/rainier#97]
It might be convenient to have regularly published nightly or publish-on-merge snapshot releases on Sonatype snapshots.

**Comment by avi-stripe** [comment]
I don't think this is practical to automate because publishing to sonatype requires signing the artifacts which involves me entering a passphrase. Does anyone know what best practices are here? @travisbrown-stripe @andyscott-stripe ?

**Comment by travisbrown-stripe** [comment]
It's possible to encode all the stuff that's needed and make Travis CI publish snapshots. There are guides I've used and could find, but I personally hate maintaining and supporting snapshot releases, so I just don't do it for any of my projects now.

**Comment by andyscott** [comment]
I second what Travis said.

**Comment by avi-stripe** [comment]
Closing as wontfix for now; I'm hoping we keep an aggressive enough release schedule that this isn't needed.
